//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artikl()
        {
            this.Stavka_kosarice = new HashSet<Stavka_kosarice>();
            this.Stavka_narudzbe = new HashSet<Stavka_narudzbe>();
        }
    
        public int artikl_id { get; set; }
        public string naziv { get; set; }
        public Nullable<double> cijena { get; set; }
        public string proizvodac { get; set; }
        public string opis { get; set; }
        public Nullable<int> kolicina { get; set; }
        public Nullable<int> vrsta_artikla { get; set; }
        public Nullable<double> snizena_cijena { get; set; }
        public Nullable<System.DateTime> datum_dodavanja { get; set; }
        public byte[] slika { get; set; }
    
        public virtual Vrsta_artikla Vrsta_artikla1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavka_kosarice> Stavka_kosarice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavka_narudzbe> Stavka_narudzbe { get; set; }
    }
}
