//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korisnik()
        {
            this.Narudzbas = new HashSet<Narudzba>();
        }
    
        public int korisnik_id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string email { get; set; }
        public string korisnicko_ime { get; set; }
        public string lozinka { get; set; }
        public string grad { get; set; }
        public string adresa { get; set; }
        public string postanski_broj { get; set; }
        public Nullable<int> kosarica { get; set; }
        public Nullable<int> tip_korisnika { get; set; }
    
        public virtual Kosarica Kosarica1 { get; set; }
        public virtual Tip_korisnika Tip_korisnika1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudzba> Narudzbas { get; set; }
    }
}
