//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PI20_011_DBEntities : DbContext
    {
        public PI20_011_DBEntities()
            : base("name=PI20_011_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artikl> Artikls { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<Kosarica> Kosaricas { get; set; }
        public virtual DbSet<Nacin_placanja> Nacin_placanja { get; set; }
        public virtual DbSet<Narudzba> Narudzbas { get; set; }
        public virtual DbSet<Podaci_o_placanju> Podaci_o_placanju { get; set; }
        public virtual DbSet<Stanje_narudzbe> Stanje_narudzbe { get; set; }
        public virtual DbSet<Stavka_kosarice> Stavka_kosarice { get; set; }
        public virtual DbSet<Stavka_narudzbe> Stavka_narudzbe { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tip_korisnika> Tip_korisnika { get; set; }
        public virtual DbSet<Vrsta_artikla> Vrsta_artikla { get; set; }
    }
}
