//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Podaci_o_placanju
    {
        public int placanje_id { get; set; }
        public string broj_racuna { get; set; }
        public string kontrolni_broj { get; set; }
        public Nullable<System.DateTime> vrijedi_do { get; set; }
        public Nullable<int> broj_narudzbe { get; set; }
        public Nullable<int> nacin_placanja { get; set; }
    
        public virtual Nacin_placanja Nacin_placanja1 { get; set; }
        public virtual Narudzba Narudzba { get; set; }
    }
}
