//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artikl()
        {
            this.Stavka_kosarice = new HashSet<Stavka_kosarice>();
            this.Stavka_narudzbe = new HashSet<Stavka_narudzbe>();
        }
    
        public int Artikl_Id { get; set; }
        public string Naziv { get; set; }
        public Nullable<double> Cijena { get; set; }
        public string Proizvodac { get; set; }
        public string Opis { get; set; }
        public Nullable<int> Kolicina { get; set; }
        public Nullable<int> VrstaArtikla { get; set; }
        public Nullable<double> Popust { get; set; }
        public Nullable<System.DateTime> DatumDodavanja { get; set; }
        public byte[] Slika { get; set; }
    
        public virtual Vrsta_artikla Vrsta_artikla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavka_kosarice> Stavka_kosarice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavka_narudzbe> Stavka_narudzbe { get; set; }
    }
}
