//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Narudzba()
        {
            this.Podaci_o_placanju = new HashSet<Podaci_o_placanju>();
            this.Stavka_narudzbe = new HashSet<Stavka_narudzbe>();
        }
    
        public int Narudzba_Id { get; set; }
        public string GradDostave { get; set; }
        public string AdresaDostave { get; set; }
        public Nullable<System.DateTime> DatumNarudzbe { get; set; }
        public Nullable<int> StanjeNarudzbe { get; set; }
        public Nullable<int> KorisnikId { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Stanje_narudzbe Stanje_narudzbe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Podaci_o_placanju> Podaci_o_placanju { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavka_narudzbe> Stavka_narudzbe { get; set; }
    }
}
