//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Podaci_o_placanju
    {
        public int Placanje_Id { get; set; }
        public string BrojRacuna { get; set; }
        public string KontrolniBroj { get; set; }
        public Nullable<System.DateTime> VrijediDo { get; set; }
        public Nullable<int> BrojNarudzbe { get; set; }
        public Nullable<int> NacinPlacanja { get; set; }
    
        public virtual Nacin_placanja Nacin_placanja { get; set; }
        public virtual Narudzba Narudzba { get; set; }
    }
}
