//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavka_narudzbe
    {
        public int Artikl_Id { get; set; }
        public int Narudzba_Id { get; set; }
        public Nullable<int> Kolicina { get; set; }
        public Nullable<double> Cijena { get; set; }
    
        public virtual Artikl Artikl { get; set; }
        public virtual Narudzba Narudzba { get; set; }
    }
}
